# Generated by Django 4.0.6 on 2022-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('size', models.CharField(max_length=200, verbose_name='Size')),
                ('observations', models.TextField(null=True, verbose_name='Observations')),
                ('brand', models.CharField(max_length=200, verbose_name='Brand')),
                ('inventory', models.IntegerField(default=0, verbose_name='Inventory')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Image')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
